// AUTO-GENERATED by scripts/benchmark-models.mjs (2026-06-15T13:57:17.970Z)
// Fastest NVIDIA NIM chat models — generation throughput >= 40.8 tok/s
// (>= 1.3x the 31.4 tok/s median; utility/embedding/safety models excluded)
export const FAST_MODEL_IDS = new Set([
  "meta/llama-3.2-1b-instruct",
  "google/diffusiongemma-26b-a4b-it",
  "mistralai/mistral-small-4-119b-2603",
  "openai/gpt-oss-20b",
  "nvidia/nemotron-3-nano-30b-a3b",
  "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning",
  "nvidia/nemotron-mini-4b-instruct",
  "mistralai/mistral-large-3-675b-instruct-2512",
  "openai/gpt-oss-120b",
  "stepfun-ai/step-3.5-flash",
  "meta/llama-3.1-8b-instruct",
  "meta/llama-4-maverick-17b-128e-instruct",
  "mistralai/ministral-14b-instruct-2512",
  "nvidia/nvidia-nemotron-nano-9b-v2",
]);
